import Footer from '@/components/Footer';
import './globals.css';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen max-w-xl mx-auto overflow-hidden bg-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
